version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - ./index.php:/var/www/html/index.php
      - ./setVersion.sh:/usr/local/bin/setVersion.sh
      - ./nginxVersion.env:/var/nginxVersion.env
    command: >
      /bin/bash -c "/usr/local/bin/setVersion.sh
      && /usr/bin/supervisord"
    env_file:
      - ./nginxVersion.env
    deploy:
      restart_policy:
          condition: on-failure # doesnt seem to be actually restarting, target was to force container to restart once after compose up by exiting with code
          delay: 5s
          max_attempts: 1

